version: '3.8'

services:
  app:
    build: 
      context: .
      target: base
    ports:
      - "3000:3000"
    environment:
      - MONGO_URL=mongodb://mongodb:27017/memory-game
      - NODE_ENV=dev
      - API_URL=http://localhost
      - PORT=3000
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/health"]
      interval: 5s
      timeout: 3s
      retries: 3
      start_period: 5s
    depends_on:
      mongodb:
        condition: service_healthy
      seeder:
        condition: service_completed_successfully
    volumes:
      - .:/app
      - /app/node_modules
    command: >
      sh -c "
        if [ -f bun.lock ]; then
          bun run dev;
        elif [ -f pnpm-lock.yaml ]; then
          pnpm run dev;
        elif [ -f yarn.lock ]; then
          yarn dev;
        else
          npm run dev;
        fi"

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 5s
      timeout: 3s
      retries: 3
    volumes:
      - mongodb_data:/data/db

  seeder:
    build:
      context: .
      target: base
    environment:
      - MONGO_URL=mongodb://mongodb:27017/memory-game
      - NODE_ENV=dev
    depends_on:
      mongodb:
        condition: service_healthy
    volumes:
      - .:/app
      - /app/node_modules
    command: >
      sh -c "
        if [ -f bun.lock ]; then
          bun run seed;
        elif [ -f pnpm-lock.yaml ]; then
          pnpm run seed;
        elif [ -f yarn.lock ]; then
          yarn seed;
        else
          npm run seed;
        fi"
    restart: "no"

volumes:
  mongodb_data: 